### PR TITLE
Add support for older java versions

### PR DESCRIPTION
**Pull request by mattsheppard**
See: #1

### CODE REVIEW

**Comment by pearj** [comment]
I discovered that you need 1.5 if you want your test to be able to run.

**Comment by mattsheppard** [comment]
Indeed - I figured Travis would tell me what I needed - Now to try and remember how we did JUnit before annotations :)

**Comment by pearj** [comment]
I started using Java at 1.5, so I never had to experience it ;)

**Comment by mattsheppard** [comment]
Ok, all going to plan, 0.0.2 should be in maven central in a little while, and ought to work back as far as Java 1.4.

**Pull request merged**
