### PR TITLE
Upgrade to JNA 5.7.0 to fix problems with Apple M1 (Silicon)

### PR DESCRIPTION
**Pull request by ghost**
When building a project on Apple Silicon (arm64), gethostname4J failed because JNA wasn't able to load the C library. A similar issue was reported here:

https://github.com/korlibs/korge/issues/335

Updating JNA fixed the problem of building my project with Silicon and a native Java 11 SDK.

### CODE REVIEW

**Comment by mattsheppard** [comment]
No objection to it, but it seems to work fine on an M1 machine for me without this change. I'd be interested if you have any guesses how our environments might differ.

**Comment by 837** [comment]
+1 need this fix for my machine
@mattsheppard maybe you updated your local jna files?

**Comment by ghost** [comment]
> No objection to it, but it seems to work fine on an M1 machine for me without this change. I'd be interested if you have any guesses how our environments might differ.

I have no real idea. I am running Monterey, and it's a rather fresh install. For me, the problem also vanished after a succesful build. Could be that there's some JNA artificats cached somewhere, which then also allow it to be used with older JNA versions. But that's speculation.

**Comment by mattsheppard** [comment]
No worries - Thanks for the reply in any case.

I'll merge this and aim to actually release a version sometime soon.

**Comment by ghost** [comment]
> I'll merge this and aim to actually release a version sometime soon.

Thanks. Gentle reminder: Matt, any chance to get a release soon?

**Comment by mattsheppard** [comment]
Thanks for the reminder - v1.0.0 should be up with this change as soon as maven central propagates it!

**Pull request merged**
